/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAT_H_RPCGEN
#define _MAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct r_times_X {
	struct {
		u_int X_len;
		int *X_val;
	} X;
	int X_size;
	float r;
};
typedef struct r_times_X r_times_X;

struct rX {
	struct {
		u_int prod_len;
		float *prod_val;
	} prod;
};
typedef struct rX rX;

#define MAT_PROG 0x23350001
#define MAT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define product 3
extern  rX * product_1(r_times_X *, CLIENT *);
extern  rX * product_1_svc(r_times_X *, struct svc_req *);
extern int mat_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define product 3
extern  rX * product_1();
extern  rX * product_1_svc();
extern int mat_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_r_times_X (XDR *, r_times_X*);
extern  bool_t xdr_rX (XDR *, rX*);

#else /* K&R C */
extern bool_t xdr_r_times_X ();
extern bool_t xdr_rX ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAT_H_RPCGEN */
