/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mat.h"

rX *
product_1_svc(r_times_X *argp, struct svc_req *rqstp)
{
	static rX  result;

	/*
	 * insert server code here
	 */

	return &result;
}
