/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "opera.h"


void
ope_prog_1(char *host)
{
	CLIENT *clnt;
	EsMat  *result_1;
	r_times_Mat  product_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, OPE_PROG, OPE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

int flag=1;
	int n;
	float r;

	do{
		char choice;			
		printf("Presiona 1 para multiplicar\n");		
		printf("cualquier otra cosa para salir\n");
		printf("Valor: ");
		scanf("%c", &choice);		
		
	if(choice=='1'){
			///////////////////////////////////////////////////////
			//r*X[]
			///////////////////////////////////////////////////////
			printf("Ingresa el valor de X[]: ");
			scanf("%d", &n);
		
			printf("\n");
			
			product_1_arg.Mat.Mat_len=n;
			product_1_arg.Mat_size=n;
			product_1_arg.Mat.Mat_val=(int *) malloc(n*sizeof(int));
			
			for(int i=0;i<n;i++)
			{
				printf("X[%d] = ", i);
				scanf("%d", &product_1_arg.Mat.Mat_val[i]);	
			}
			
			printf("Ingresa el escalar: ");
			scanf("%f", &r);
			
			product_1_arg.Es=r;
			
			printf("\n");

		result_1 = product_1(&product_1_arg, clnt);
		if (result_1 == (EsMat *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf("\n");
				for(int i=0;i<n;i++)
					printf("r*X[%d] == %.2f\n", i, result_1->prod.prod_val[i]);
				printf("\n");
		}
		
	}else{
		flag=0;
		printf("Adios\n\n");
	}
}while(flag);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ope_prog_1 (host);
exit (0);
}
