/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "opera.h"

EsMat *
product_1_svc(r_times_Mat *argp, struct svc_req *rqstp)
{
	static EsMat  result;

	printf("r*X[] function called...\n");

	result.prod.prod_len=argp->Mat_size;
	result.prod.prod_val=(float *)malloc(argp->Mat_size*sizeof(float));
	
	int i;
	
	for(i=0;i<argp->Mat_size;i++)
		result.prod.prod_val[i]=argp->Es*argp->Mat.Mat_val[i];

	return &result;
}
