/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERA_H_RPCGEN
#define _OPERA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct EsMat {
	struct {
		u_int prod_len;
		float *prod_val;
	} prod;
};
typedef struct EsMat EsMat;

struct r_times_Mat {
	struct {
		u_int Mat_len;
		int *Mat_val;
	} Mat;
	int Mat_size;
	float Es;
};
typedef struct r_times_Mat r_times_Mat;

#define OPE_PROG 0x23350034
#define OPE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define product 3
extern  EsMat * product_1(r_times_Mat *, CLIENT *);
extern  EsMat * product_1_svc(r_times_Mat *, struct svc_req *);
extern int ope_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define product 3
extern  EsMat * product_1();
extern  EsMat * product_1_svc();
extern int ope_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_EsMat (XDR *, EsMat*);
extern  bool_t xdr_r_times_Mat (XDR *, r_times_Mat*);

#else /* K&R C */
extern bool_t xdr_EsMat ();
extern bool_t xdr_r_times_Mat ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERA_H_RPCGEN */
