/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "opera.h"

bool_t
xdr_EsMat (XDR *xdrs, EsMat *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->prod.prod_val, (u_int *) &objp->prod.prod_len, 100,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_r_times_Mat (XDR *xdrs, r_times_Mat *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->Mat.Mat_val, (u_int *) &objp->Mat.Mat_len, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Mat_size))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->Es))
		 return FALSE;
	return TRUE;
}
