/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "opera.h"

EsMat *
product_1_svc(r_times_Mat *argp, struct svc_req *rqstp)
{
	static EsMat  result;

	/*
	 * insert server code here
	 */

	return &result;
}
